# Generated by Django 4.2.30 on 2026-06-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
