# Generated by Django 4.2.30 on 2026-06-16 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userprofile_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('job_role', models.CharField(blank=True, default='', max_length=255)),
                ('tech_stack', models.CharField(blank=True, default='', max_length=500)),
                ('total_questions', models.IntegerField(default=0)),
                ('current_question', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('summary', models.TextField(blank=True, default='')),
                ('overall_score', models.FloatField(default=0.0)),
                ('strengths', models.TextField(blank=True, default='')),
                ('improvements', models.TextField(blank=True, default='')),
                ('recommendations', models.TextField(blank=True, default='')),
                ('interviews_analyzed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weekly Feedback',
                'verbose_name_plural': 'Weekly Feedbacks',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_audio_url', models.CharField(blank=True, default='', max_length=500)),
                ('answer_text', models.TextField(blank=True, default='')),
                ('answer_audio_url', models.CharField(blank=True, default='', max_length=500)),
                ('score', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True, default='')),
                ('strengths', models.TextField(blank=True, default='')),
                ('improvements', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.interview')),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'ordering': ['order'],
            },
        ),
    ]
